### PR TITLE
Add encoding types

### PR DESCRIPTION
**Pull request by Mallets**
Align Python bindings with recent changes introduced by https://github.com/eclipse-zenoh/zenoh/pull/1174

### CODE REVIEW

**Comment by Mallets** [comment]
@wyfo would you mind reviewing this PR?

**Comment by wyfo** [comment]
Why did you modified error handling?

**Comment by Mallets** [comment]
`deserialize()` return `ZDeserializeError` that does not implement `Display`. But `IntoPyErr` requires `E: ToString` to convert any error into a `PyErr`. Therefore the `.map_err()`.

**Comment by wyfo** [comment]
Why doesn't `ZDeserializeError` implement `std::error::Error`? That's neither intuitive, nor conventional for type suffixed with "Error". I think that instead of modifying the python code, we should fix the Rust implementation.

**Comment by Mallets** [comment]
To be resynced and merged after https://github.com/eclipse-zenoh/zenoh/pull/1192

**Comment by wyfo** [comment]
You need to update `Cargo.lock` and retrigger the CI.

**Comment by Mallets** [comment]
Done, waiting the CI to complete.

**Comment by wyfo** [comment]
OK for me
