### ISSUE TITLE
Failed building wheel for eclipse-zenoh

### ISSUE THREAD

**Issue by lottz** [eclipse-zenoh/zenoh-python#72]
### Describe the bug

Standard python example running on Raspberry PI
Code:
```
from zenoh import Zenoh
import random
import time

random.seed()

def read_temp():
    return random.randint(15, 30)

def run_sensor_loop(w):
    # read and produce a temperature every second
    while True:
        t = read_temp()
        w.put('/myfactory/machine1/temp',t)
        print (t)
        time.sleep(15)

if __name__ == "__main__":
    z = Zenoh({'peer': 'tcp/127.0.0.1:7447'})
    w = z.workspace('/')
    run_sensor_loop(w)
```
Error Message:
```
Traceback (most recent call last):
  File "zenoh_producer.py", line 27, in <module>
    run_sensor_loop(w)
  File "zenoh_producer.py", line 20, in run_sensor_loop
    w.put('/myfactory/machine1/temp',t)
  File "/usr/local/lib/python3.7/dist-packages/zenoh/workspace.py", line 50, in put
    self.rt.write_data(
AttributeError: 'dict' object has no attribute 'write_data'
```
Any hints what led to this error message?

### To reproduce

1. Start Zenoh Broker
2. Execute provided code
3. Works on Ubuntu 22.04 but led to the shown error on ARM / Raspberry Pi OS.

### System info

No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
 Operating System: Raspbian GNU/Linux 10 (buster)
 Kernel: Linux 5.10.103-v7l+
 Architecture: arm

- Rust: rustc 1.63.0 (4b91a6ea7 2022-08-08)
- Python 3.7.3
- The zenoh router v0.5.0-beta.8-326-g70d7b22

**Comment by JEnoch** [comment]
It seems that you're Python environment is using an old version of Zenoh Python (probably 0.4.0 looking at the log wrt. workspace.py line 50).
You need to use a version that matches your zenoh router (v0.5.0-beta.8-326-g70d7b22 == v0.5.0-beta.9).

So, please, can you try to uninstall any previous version of zenoh and reinstall the version 0.5.0-b9:
```bash
pip uninstall eclipse-zenoh zenoh
pip install eclipse-zenoh==0.5.0b9
```

**Comment by lottz** [comment]
```
Uninstalling zenoh-0.4.0:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/zenoh-0.4.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/zenoh/*
Proceed (y/n)? y
  Successfully uninstalled zenoh-0.4.0
```
When trying to install the 0.5 Version:
```
--extern event_listener=/tmp/pip-install-s0go_vz5/eclipse-zenoh/target/release/deps/libevent_listener-e772c0c8cfb99780.rmeta --cap-lints allow`
  error: attributes are not yet allowed on `if` expressions
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-lock-2.4.0/src/mutex.rs:165:13
      |
  165 |             #[cfg(not(target_arch = "wasm32"))]
      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  error: aborting due to previous error
  
  error: could not compile `async-lock`.
  
  Caused by:
    process didn't exit successfully: `rustc --crate-name async_lock --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-lock-2.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=9d1fd37a6929c054 -C extra-filename=-9d1fd37a6929c054 --out-dir /tmp/pip-install-s0go_vz5/eclipse-zenoh/target/release/deps -L dependency=/tmp/pip-install-s0go_vz5/eclipse-zenoh/target/release/deps --extern event_listener=/tmp/pip-install-s0go_vz5/eclipse-zenoh/target/release/deps/libevent_listener-e772c0c8cfb99780.rmeta --cap-lints allow` (exit code: 1)
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib` failed with code 101
  
  ----------------------------------------
  Failed building wheel for eclipse-zenoh
  Running setup.py clean for eclipse-zenoh
Failed to build eclipse-zenoh
```
This error occurs...

**Comment by JEnoch** [comment]
Now it seems that `pip` calls an old version of `rustc`.
The 2 messages refer to features that have been added to `rustc` a long time ago:

- `attributes are not yet allowed on 'if' expressions` was solved with rust [1.43.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1430-2020-04-23) (see "Language" section, 2nd bullet)
- `use of unstable library feature 'matches_macro'` was stabilized with rust [1.42.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1420-2020-03-12) (see "Stabilized APIs" section, `matches!")

Buster has a [rustc package](https://packages.debian.org/buster/rustc) which is an old version (1.41.1).
If this package is install on your Raspbian, you should probably remove it to make sure that `pip` will use the correct `rustc` version - i.e. the **1.63.0** you probably installed via `rustup` and which should be found in `~/.cargo/bin`

**Comment by lottz** [comment]
Unfortunately setup tools does not seem to recognize the rustu toolchain (PATH is set)

```
sudo pip3 install eclipse-zenoh==0.5.0b9
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting eclipse-zenoh==0.5.0b9
  Using cached https://files.pythonhosted.org/packages/ca/d7/1625f0d45ddb37f31bf9f9dc9de5a92ce1fa9458d1c13076ca6326b544d2/eclipse-zenoh-0.5.0b9.tar.gz
  Installing build dependencies ... done
Building wheels for collected packages: eclipse-zenoh
  Running setup.py bdist_wheel for eclipse-zenoh ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-538i0qpz/eclipse-zenoh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-_o7e_gs_ --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  running build_rust
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.  
  ----------------------------------------
  Failed building wheel for eclipse-zenoh
  Running setup.py clean for eclipse-zenoh
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-538i0qpz/eclipse-zenoh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  running clean
  'build/lib.linux-armv7l-cpython-37' does not exist -- can't clean it
  'build/bdist.linux-armv7l' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
  running clean_rust
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.  
  To update pip, run:  
      pip install --upgrade pip  
  and then retry package installation.
  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    ----------------------------------------
  Failed cleaning build dir for eclipse-zenoh
Failed to build eclipse-zenoh
Installing collected packages: eclipse-zenoh
  Running setup.py install for eclipse-zenoh ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-538i0qpz/eclipse-zenoh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-yen6ckbs/install-record.txt --single-version-externally-managed --compile:
    running install
    /tmp/pip-build-env-hnpovx5_/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_ext
    running build_rust
    error: can't find Rust compiler
    
    If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-538i0qpz/eclipse-zenoh/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-yen6ckbs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-538i0qpz/eclipse-zenoh/
```
Where does the build configuration need to be adjusted?

**Comment by JEnoch** [comment]
What is your version of `pip`? **19.3.1** minimum is required to build the from source distribution package.

Note that while for 0.5.0b9 release we didn't manage to pre-build wheels for ARMs platforms, they will be available for the 0.6.0 release to come soon.

**Comment by lottz** [comment]
`pip 22.2.2 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)`
Ok then i ll just wait for the 0.6.0 release :-)
